stages: 
  probe:
    cmd: PYTHONPATH= python pipelines/prepare/example.py 
    wdir: ../..
    deps:
      - pipelines/prepare/example.py
      - pipelines/prepare/util.py
      - data/example-vis.csv
    outs:
      - src/_data/example/dashboard.csv:
          cache: false
      - src/_data/example/line_chart.csv:
          cache: false
      - src/_data/example/stats.json:
          cache: false
      