stages: 
  probe:
    cmd: PYTHONPATH= python pipelines/extract/probe.py 
    # always_changed: true
    wdir: ../..
    deps:
      - pipelines/extract/probe.py
      - pipelines/extract/utils.py
    outs:
      - data/lookups:
          cache: false
          persist: false
    