stages: 
  extract:
    wdir: ../..
    cmd: statxplore --api_key $STATXPLORE_API_KEY -q pipelines/extract/test.json -o working/test.csv
    deps: 
      - pipelines/extract/test.json
    outs:
     - working/test.csv:
        cache: false
        persist: false