stages: 
  # extract:
  #   wdir: ../..
  #   cmd: statxplore --api_key $STATXPLORE_API_KEY -q pipelines/extract/test.json -o working/test.csv
  #   deps: 
  #     - pipelines/extract/test.json
  #   outs:
  #    - working/test.csv:
  #       cache: false
  #       persist: false
  extract:
    cmd: PYTHONPATH= python pipelines/extract/hbai/extract.py
    wdir: ../..
    deps:
      - pipelines/extract/hbai/extract.py
    