stages: 
  # probe:
  #   cmd: PYTHONPATH= python pipelines/extract/probe.py 
  #   # always_changed: true
  #   wdir: ../..
  #   deps:
  #     - pipelines/extract/probe.py
  #     - pipelines/extract/utils.py
  #   outs:
  #     - data/lookups:
  #         cache: false
  #         persist: false
  extract:
    cmd: PYTHONPATH= python pipelines/extract/extract.py 
    # always_changed: true
    wdir: ../..
    deps:
      - pipelines/extract/extract.py
      - pipelines/extract/utils.py
      - data/lookups
    outs:
      - data/csv:
          cache: false
          persist: false  