vars:
  - top: '../..'
stages:
  transform-geojson:
    cmd: papermill geojson.ipynb output/geojson.ipynb
    deps:
      - geojson.ipynb
      - loaders.py
      - params.py
      - ${top}/data/geo/cauth22.geojson
      - ${top}/data/geo/cty22.geojson
      - ${top}/data/geo/lad22.geojson
      - ${top}/data/geo/panrgn22.geojson
      - ${top}/data/geo/rgn22.geojson
      - ${top}/data/geo/wd22.geojson
    outs:
      - ${top}/data/interim/shapes.parquet:
          persist: false
          cache: false

  generate-list:
    cmd: python generate-list.py
    deps:
      - generate-list.py
      - params.py
      - ${top}/data/interim/shapes.parquet
    outs:
      - places.yaml:
          cache: false
          persist: false

  transform:
    cmd: papermill transform.ipynb output/transform.ipynb
    deps:
      - transform.ipynb
      - params.py
      - places.yaml
      - geo.py
      - ${top}/data/geo/geography_tree.csv
      - ${top}/data/population-estimates/population-estimates.csv
      - ${top}/data/council-tax-support/council-tax-support.csv
      - ${top}/data/clif/clif_REL.csv
    outs:
      - ${top}/data/interim/place_data.parquet:
          persist: false
          cache: false
      - ${top}/data/interim/place_data.json:
          persist: false
          cache: false
      - ${top}/data/interim/current_rental_prices.csv:
          persist: false
          cache: false
      - ${top}/data/interim/house_prices.csv:
          persist: false
          cache: false


  # generate_places:
  #   cmd: python generate_params.py
  #   deps:
  #     - generate_params.py
  #     - ../../../src/_data/places.json
  #   outs:
  #     - params.yaml:
  #         cache: false
  #         persist: false
  # prepare-place:
  #   foreach: ${places}
  #   do:
  #     cmd: python prepare.py ${item}
  #     deps:
  #       - prepare.py
  #       - ${top}/data/interim/place_data.parquet
  #       - ${top}/data/interim/shapes.parquet
      # outs:
      #   - ${top}/src/place/${item}/index.njk:
      #       persist: false
      #       cache: false
        # - ${top}/src/_data/place_data/${item}/map.geojson:
        #     persist: false
        #     cache: false
  prepare-batch:
    cmd: python batch.py
    deps:
      - batch.py
      - params.py
      - places.yaml
      - prepare.py
      - ${top}/data/interim/place_data.parquet
      - ${top}/data/interim/shapes.parquet
    outs:
      - ${top}/src/_data/place/:
          cache: false
          persist: false
