vars:
  - top: '../..'
stages:
  list:
    cmd: papermill list-metadata.ipynb output/list-metadata.ipynb
    always_changed: true
    deps:
      - list-metadata.ipynb
      - ${top}/data
    outs:
      - catalogue.yaml:
          persist: true
          cache: false
  prepare:
    cmd: papermill prep-metadata.ipynb output/prep-metadata.ipynb
    deps:
      - prep-metadata.ipynb
      - catalogue.yaml
    outs:
      - ${top}/src/_data/metadata/catalogue.json:
          persist: false
          cache: false

