vars:
  - top: '../..'
stages:
  extract-hbai:
    cmd: papermill hbai.ipynb ${top}/data/_working/output/hbai.ipynb
    always_changed: true
    deps:
      - hbai.ipynb
      - api.py
      - json/data/HBAI.json
    outs: 
      - ${top}/data/hbai/by_age_category.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_age_of_youngest_child.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_ethnic_group.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_marital_status.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_number_of_children.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_savings_and_investments.csv:
          cache: false
          persist: false
      - ${top}/data/hbai/by_tenure_type.csv:
          cache: false
          persist: false
      - ${top}/data/interim/hbai_by_ethnic_group.csv:
          cache: false
          persist: false
      - ${top}/data/interim/hbai_by_marital_status.csv:
          cache: false
          persist: false
  extract:
    cmd: python pipelines/statxplore/extract.py
    wdir: ../..
    deps:
      - pipelines/statxplore/extract.py
      - pipelines/statxplore/api.py
      - pipelines/statxplore/json/data
      - data/geo/geography_lookup.csv
    outs: 
      - data/clif/clif_ABS.csv:
          cache: false
          persist: false
      - data/clif/clif_REL.csv:
          cache: false
          persist: false
      - data/smi/smi_in_payment_amount.csv:
          cache: false
          persist: false
      - data/smi/smi_loans_in_payment_households.csv:
          cache: false
          persist: false
      - data/HB/claimants.csv:
          cache: false
          persist: false
