geography:
  code: 'E12000003'
  name: 'England'
  type: 'N'

file:
  place: "src/_data/places/the_north.yml"
  code_start: "E12"
# variable:
#   code: 
#   name:
# dates: 
region: "the_north"
thing:  council_tax_support
