vars:
  - top: '../../..'
stages:
  download-files:
    cmd: python get-files.py
    deps:
      - get-files.py
    outs:
      - ${top}/data-raw/dwelling-stock/subnationaldwellingstockbytenure2021.xlsx:
          cache: false
          persist: false
  rental-prices:
    cmd: papermill rental_prices.ipynb ${top}/data/_working/output/rental_prices.ipynb
    deps:
      - ${top}/pipelines/spotlight/housing/rental_prices.ipynb
      #- ${top}/data/rental-prices/rental-prices.csv
    outs: 
      - ${top}/data-mart/rental-prices/most_recent_rental_prices.parquet:
          cache: false
          persist: false
  earnings-rent-ratio:
    cmd: papermill rents_to_earnings.ipynb ${top}/data/_working/output/rents_to_earnings.ipynb
    deps:
      - ${top}/pipelines/spotlight/housing/rents_to_earnings.ipynb
      #- ${top}/data/rental-prices/rental-prices.csv
      - ${top}/data/ashe/weekly-earnings.csv
    outs: 
      - ${top}/data-mart/ashe/rent-earning-ratio.parquet:
          cache: false
          persist: false 
  dwellings:
    cmd: papermill dwelling_stock.ipynb ${top}/data/_working/output/dwelling_stock.ipynb
    deps:
      - ${top}/pipelines/spotlight/housing/dwelling_stock.ipynb
      - ${top}/data-raw/dwelling-stock/subnationaldwellingstockbytenure2021.xlsx
    outs: 
      - ${top}/data-mart/dwelling-stock/dwelling-stock.parquet:
          cache: false
          persist: false   