vars:
  - top: '../../..'
stages:
  rental-prices:
    cmd: papermill rental_prices.ipynb ${top}/data/_working/output/rental_prices.ipynb
    deps:
      - ${top}/pipelines/spotlight/housing/rental_prices.ipynb
      #- ${top}/data/rental-prices/rental-prices.csv
    outs: 
      - ${top}/data/rental-prices/most_recent_rental_prices.csv:
          cache: false
          persist: false
  earnings-rent-ratio:
    cmd: papermill rents_to_earnings.ipynb ${top}/data/_working/output/rents_to_earnings.ipynb
    deps:
      - ${top}/pipelines/spotlight/housing/rents_to_earnings.ipynb
      #- ${top}/data/rental-prices/rental-prices.csv
    outs: 
      - ${top}/data/rental-prices/rent-earning-ratio.csv:
          cache: false
          persist: false    