vars:
  - top: '../../..'
stages:
  transform:
    cmd: papermill transform.ipynb output/transform.ipynb
    deps:
      - transform.ipynb
      - ${top}/data/geo/geography_tree.csv
      - ${top}/data/population-estimates/population-estimates.csv
      - ${top}/data/council-tax-support/council-tax-support.csv
      - ${top}/data/clif/clif_REL.csv
    outs:
      - ${top}/data/interim/place_data.parquet:
          persist: false
          cache: false

  transform-geojson:
    cmd: papermill geojson.ipynb output/geojson.ipynb
    deps:
      - geojson.ipynb
      - ${top}/data/geo/cauth22.geojson
      - ${top}/data/geo/cty22.geojson
      - ${top}/data/geo/lad22.geojson
      - ${top}/data/geo/panrgn22.geojson
      - ${top}/data/geo/rgn22.geojson
      - ${top}/data/geo/wd22.geojson
    outs:
      - ${top}/data/interim/shapes.parquet:
          persist: false
          cache: false

  # generate_places:
  #   cmd: python generate_params.py
  #   deps:
  #     - generate_params.py
  #     - ../../../src/_data/places.json
  #   outs:
  #     - params.yaml:
  #         cache: false
  #         persist: false
  prepare-place:
    foreach: ${places}
    do:
      cmd: python prepare.py ${item}
      deps:
        - prepare.ipynb
        - ${top}/data/interim/place_data.parquet
      outs:
        - ${top}/src/_data/place_data/${item}/place_data.csv:
            persist: false
            cache: false
