stages:
  # ashe = COLLECTION - big one - more work required - unzip from file, etc

  # claimant-count:
  #   cmd: Rscript R/claimant-count.R
  #   wdir: ..
  #   deps:
  #     - R/claimant-count.R
  #   outs:
  #     - data/claimant-count/claimant-count.csv:
  #         persist: false
  #         cache: false

  # cstop-households = COLLECTION
  # fuel-poverty = COLLECTION
  # gva - from EDD
  # house-prices
  # imd 
  # individual-insolvencies = COLLECTION
  # R/jobs-below-living-wage.R
  # R/labour-market.R
  labour-market:
    cmd: Rscript R/labour-market.R
    always_changed: true
    wdir: ..
    deps:
      - R/labour-market.R
    outs:
      - data/labour-market/labour-market.csv:
          persist: false
          cache: false

  # R/local-council-tax-support.R
  # R/mortgage-landlord-possession.R
  # R/population-estimates.R
  # R/rental-prices.R
  # R/statutory-homelessness.R
  