# TODO Fix any frozen pipelines in this file

stages:
  # ashe = COLLECTION - big one - more work required - unzip from file, etc
  ashe:
    cmd: Rscript R/ashe.R
    always_changed: true
    wdir: ..
    deps:
      - R/ashe.R
    outs:
      - data/ashe/weekly-earnings.csv:
          persist: false
          cache: false
      - data-mart/ashe/weekly-earnings.parquet:
          persist: false
          cache: false

  claimant-count:
    cmd: Rscript R/claimant-count.R
    always_changed: true
    wdir: ..
    deps:
      - R/claimant-count.R
    outs:
      - data/claimant-count/claimant-count.csv:
          persist: false
          cache: false
      - data-mart/claimant-count/claimant-count.parquet:
          persist: false
          cache: false

  # ctsop-households = COLLECTION
  ctsop-households:
    cmd: Rscript R/ctsop-households.R
    always_changed: true
    wdir: ..
    deps:
      - R/ctsop-households.R
    outs:
      - data/households/households.csv:
          persist: false
          cache: false
      - data-mart/households/households.parquet:
          persist: false
          cache: false

  # fuel-poverty = COLLECTION
  fuel-poverty:
    cmd: Rscript R/fuel-poverty.R
    always_changed: true
    wdir: ..
    deps:
      - R/fuel-poverty.R
    outs:
      - data/fuel-poverty/fuel-poverty.csv:
          persist: false
          cache: false
      - data-mart/fuel-poverty/fuel-poverty.parquet:
          persist: false
          cache: false

  gender-pay-gap:
    cmd: Rscript R/gender-pay-gap.R
    always_changed: true
    wdir: ..
    deps:
      - R/gender-pay-gap.R
    outs:
      - data/gender-pay-gap/gender-pay-gap.csv:
          persist: false
          cache: false
      - data-mart/gender-pay-gap/gender-pay-gap.parquet:
          persist: false
          cache: false

  # gva - from EDD
  gva:
    frozen: true
    cmd: Rscript R/gva.R
    always_changed: true
    wdir: ..
    deps:
      - R/gva.R
    outs:
      - data/gva/gva.csv:
          persist: false
          cache: false


  # house-prices
  house-prices:
    cmd: Rscript R/house-prices.R
    always_changed: true
    wdir: ..
    deps:
      - R/house-prices.R
    outs:
      - data/house-prices/house-prices.csv:
          persist: false
          cache: false
      - data-mart/house-prices/house-prices.parquet:
          persist: false
          cache: false

  # imd 
  imd:
    cmd: Rscript R/imd.R
    wdir: ..
    deps:
      - R/imd.R
      - data-raw/imd/
    outs:
      - data/imd/imd.csv:
          persist: false
          cache: false
      - data-mart/imd/imd.parquet:
          persist: false
          cache: false

  # individual-insolvencies = COLLECTION
  individual-insolvencies:
    cmd: Rscript R/individual-insolvencies.R
    always_changed: true
    wdir: ..
    deps:
      - R/individual-insolvencies.R
    outs:
      - data/insolvencies/insolvencies.csv:
          persist: false
          cache: false
      - data-mart/insolvencies/insolvencies.parquet:
          persist: false
          cache: false

  # R/jobs-below-living-wage.R
  jobs-below-living-wage:
    cmd: Rscript R/jobs-below-living-wage.R
    always_changed: true
    wdir: ..
    deps:
      - R/jobs-below-living-wage.R
    outs:
      - data/jobs-below-living-wage/jobs-below-living-wage.csv:
          persist: false
          cache: false
      - data-mart/jobs-below-living-wage/jobs-below-living-wage.parquet:
          persist: false
          cache: false

  # R/labour-market.R
  labour-market:
    cmd: Rscript R/labour-market.R
    always_changed: true
    wdir: ..
    deps:
      - R/labour-market.R
    outs:
      - data/labour-market/labour-market.csv:
          persist: false
          cache: false
      - data-mart/labour-market/labour-market.parquet:
          persist: false
          cache: false

  # R/local-council-tax-support.R
  council-tax-support:
    cmd: Rscript R/local-council-tax-support.R
    always_changed: true
    wdir: ..
    deps:
      - R/local-council-tax-support.R
    outs:
      - data/council-tax-support/council-tax-support.csv:
          persist: false
          cache: false
      - data-mart/council-tax-support/council-tax-support.parquet:
          persist: false
          cache: false

  # R/mortgage-landlord-possession.R
  mortgage-landlord-possession:
    cmd: Rscript R/mortgage-landlord-possession.R
    always_changed: true
    wdir: ..
    deps:
      - R/mortgage-landlord-possession.R
    outs:
      - data/mortgage-landlord-possession/mortgage-landlord-possession.csv:
          persist: false
          cache: false
      - data-mart/mortgage-landlord-possession/mortgage-landlord-possession.parquet:
          persist: false
          cache: false

  # R/population-estimates.R
  population-estimates:
    frozen: true
    cmd: Rscript R/population-estimates.R
    always_changed: true
    wdir: ..
    deps:
      - R/population-estimates.R
    outs:
      - data/population-estimates/population-estimates.csv:
          persist: false
          cache: false


  # R/rental-prices.R
  rental-prices:
    cmd: Rscript R/rental-prices.R
    always_changed: true
    wdir: ..
    deps:
      - R/rental-prices.R
    outs:
      - data/rental-prices/rental-prices.csv:
          persist: false
          cache: false
      - data-mart/rental-prices/rental-prices.parquet:
          persist: false
          cache: false

  # R/statutory-homelessness.R
  statutory-homelessness:
    cmd: Rscript R/statutory-homelessness.R
    always_changed: true
    wdir: ..
    deps:
      - R/statutory-homelessness.R
    outs:
      - data/statutory-homelessness/statutory-homelessness.csv:
          persist: false
          cache: false
      - data-mart/statutory-homelessness/statutory-homelessness.parquet:
          persist: false
          cache: false